name: TVEpisodeMatcherMKV
options:
  bundleIdPrefix: com.example
settings:
  base:
    SWIFT_VERSION: 5.9
    DEVELOPMENT_TEAM: ""
    MACOSX_DEPLOYMENT_TARGET: "13.0"

targets:
  TVEpisodeMatcherMKV:
    type: application
    platform: macOS
    sources:
      - TVEpisodeMatcherMKV
    info:
      path: TVEpisodeMatcherMKV/Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.example.TVEpisodeMatcherMKV
        INFOPLIST_FILE: TVEpisodeMatcherMKV/Info.plist
        CODE_SIGN_STYLE: Automatic
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0
    postBuildScripts:
      - name: Bundle seconv
        script: |
          if [ -f "${SRCROOT}/tools/seconv/seconv" ]; then
            DEST="${TARGET_BUILD_DIR}/${CONTENTS_FOLDER_PATH}/Resources/Tools"
            mkdir -p "${DEST}"
            cp "${SRCROOT}/tools/seconv/seconv" "${DEST}/seconv"
            chmod +x "${DEST}/seconv"
            if [ -n "${EXPANDED_CODE_SIGN_IDENTITY:-}" ]; then
              /usr/bin/codesign --force --sign "${EXPANDED_CODE_SIGN_IDENTITY}" --timestamp=none "${DEST}/seconv" >/dev/null 2>&1 || true
            fi
          fi
