name: TVEpisodeMatcherMKV
options:
  bundleIdPrefix: com.example
settings:
  base:
    SWIFT_VERSION: 5.9
    DEVELOPMENT_TEAM: ""
    MACOSX_DEPLOYMENT_TARGET: "13.0"

targets:
  TVEpisodeMatcherMKV:
    type: application
    platform: macOS
    sources:
      - TVEpisodeMatcherMKV
      - TVEpisodeMatcherMKV/Assets.xcassets
    info:
      path: TVEpisodeMatcherMKV/Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.example.TVEpisodeMatcherMKV
        INFOPLIST_FILE: TVEpisodeMatcherMKV/Info.plist
        CODE_SIGN_STYLE: Automatic
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0
    postBuildScripts:
      - name: Bundle tools
        script: |
          set -e
          TOOLS_SRC="${SRCROOT}/tools"
          DEST="${TARGET_BUILD_DIR}/${CONTENTS_FOLDER_PATH}/Resources/Tools"

          copy_tool_dir() {
            local name="$1"
            local src="${TOOLS_SRC}/${name}"
            local dst="${DEST}/${name}"
            if [ -d "${src}" ]; then
              if [ -e "${dst}" ] && [ ! -d "${dst}" ]; then
                rm -f "${dst}"
              fi
              mkdir -p "${dst}"
              /bin/cp -R "${src}/." "${dst}"
            fi
          }

          # Clean destination to avoid permission issues from previous builds
          rm -rf "${DEST}"
          mkdir -p "${DEST}"
          copy_tool_dir seconv
          copy_tool_dir ffmpeg


          for bin in             "${DEST}/seconv/seconv"             "${DEST}/ffmpeg/ffmpeg"             "${DEST}/ffmpeg/ffprobe"; do
            if [ -f "${bin}" ]; then
              chmod +x "${bin}"
              if [ -n "${EXPANDED_CODE_SIGN_IDENTITY:-}" ]; then
                /usr/bin/codesign --force --sign "${EXPANDED_CODE_SIGN_IDENTITY}" --timestamp=none "${bin}" >/dev/null 2>&1 || true
              fi
            fi
          done

          if [ -n "${EXPANDED_CODE_SIGN_IDENTITY:-}" ]; then
            find "${DEST}" -type f \( -name "*.dylib" -o -perm -111 \) -print0 | while IFS= read -r -d '' file; do
              /usr/bin/codesign --force --sign "${EXPANDED_CODE_SIGN_IDENTITY}" --timestamp=none "${file}" >/dev/null 2>&1 || true
            done
          fi
